export const countriesData = [
    { countryName: "Afghanistan", countryCode: "AF" },
    { countryName: "Albania", countryCode: "AL" },
    { countryName: "Algeria", countryCode: "DZ" },
    { countryName: "Andorra", countryCode: "AD" },
    { countryName: "Angola", countryCode: "AO" },
    { countryName: "Antigua and Barbuda", countryCode: "AG" },
    { countryName: "Argentina", countryCode: "AR" },
    { countryName: "Armenia", countryCode: "AM" },
    { countryName: "Australia", countryCode: "AU" },
    { countryName: "Austria", countryCode: "AT" },
    { countryName: "Azerbaijan", countryCode: "AZ" },
    { countryName: "Bahamas", countryCode: "BS" },
    { countryName: "Bahrain", countryCode: "BH" },
    { countryName: "Bangladesh", countryCode: "BD" },
    { countryName: "Barbados", countryCode: "BB" },
    { countryName: "Belarus", countryCode: "BY" },
    { countryName: "Belgium", countryCode: "BE" },
    { countryName: "Belize", countryCode: "BZ" },
    { countryName: "Benin", countryCode: "BJ" },
    { countryName: "Bhutan", countryCode: "BT" },
    { countryName: "Bolivia", countryCode: "BO" },
    { countryName: "Bosnia and Herzegovina", countryCode: "BA" },
    { countryName: "Botswana", countryCode: "BW" },
    { countryName: "Brazil", countryCode: "BR" },
    { countryName: "Brunei", countryCode: "BN" },
    { countryName: "Bulgaria", countryCode: "BG" },
    { countryName: "Burkina Faso", countryCode: "BF" },
    { countryName: "Burundi", countryCode: "BI" },
    { countryName: "Cabo Verde", countryCode: "CV" },
    { countryName: "Cambodia", countryCode: "KH" },
    { countryName: "Cameroon", countryCode: "CM" },
    { countryName: "Canada", countryCode: "CA" },
    { countryName: "Central African Republic", countryCode: "CF" },
    { countryName: "Chad", countryCode: "TD" },
    { countryName: "Chile", countryCode: "CL" },
    { countryName: "China", countryCode: "CN" },
    { countryName: "Colombia", countryCode: "CO" },
    { countryName: "Comoros", countryCode: "KM" },
    { countryName: "Congo (Congo-Brazzaville)", countryCode: "CG" },
    { countryName: "Costa Rica", countryCode: "CR" },
    { countryName: "Croatia", countryCode: "HR" },
    { countryName: "Cuba", countryCode: "CU" },
    { countryName: "Cyprus", countryCode: "CY" },
    { countryName: "Czech Republic", countryCode: "CZ" },
    { countryName: "Democratic Republic of the Congo", countryCode: "CD" },
    { countryName: "Denmark", countryCode: "DK" },
    { countryName: "Djibouti", countryCode: "DJ" },
    { countryName: "Dominica", countryCode: "DM" },
    { countryName: "Dominican Republic", countryCode: "DO" },
    { countryName: "Ecuador", countryCode: "EC" },
    { countryName: "Egypt", countryCode: "EG" },
    { countryName: "El Salvador", countryCode: "SV" },
    { countryName: "Equatorial Guinea", countryCode: "GQ" },
    { countryName: "Eritrea", countryCode: "ER" },
    { countryName: "Estonia", countryCode: "EE" },
    { countryName: "Eswatini", countryCode: "SZ" },
    { countryName: "Ethiopia", countryCode: "ET" },
    { countryName: "Fiji", countryCode: "FJ" },
    { countryName: "Finland", countryCode: "FI" },
    { countryName: "France", countryCode: "FR" },
    { countryName: "Gabon", countryCode: "GA" },
    { countryName: "Gambia", countryCode: "GM" },
    { countryName: "Georgia", countryCode: "GE" },
    { countryName: "Germany", countryCode: "DE" },
    { countryName: "Ghana", countryCode: "GH" },
    { countryName: "Greece", countryCode: "GR" },
    { countryName: "Grenada", countryCode: "GD" },
    { countryName: "Guatemala", countryCode: "GT" },
    { countryName: "Guinea", countryCode: "GN" },
    { countryName: "Guinea-Bissau", countryCode: "GW" },
    { countryName: "Guyana", countryCode: "GY" },
    { countryName: "Haiti", countryCode: "HT" },
    { countryName: "Honduras", countryCode: "HN" },
    { countryName: "Hungary", countryCode: "HU" },
    { countryName: "Iceland", countryCode: "IS" },
    { countryName: "India", countryCode: "IN" },
    { countryName: "Indonesia", countryCode: "ID" },
    { countryName: "Iran", countryCode: "IR" },
    { countryName: "Iraq", countryCode: "IQ" },
    { countryName: "Ireland", countryCode: "IE" },
    { countryName: "Israel", countryCode: "IL" },
    { countryName: "Italy", countryCode: "IT" },
    { countryName: "Jamaica", countryCode: "JM" },
    { countryName: "Japan", countryCode: "JP" },
    { countryName: "Jordan", countryCode: "JO" },
    { countryName: "Kazakhstan", countryCode: "KZ" },
    { countryName: "Kenya", countryCode: "KE" },
    { countryName: "Kiribati", countryCode: "KI" },
    { countryName: "Kuwait", countryCode: "KW" },
    { countryName: "Kyrgyzstan", countryCode: "KG" },
    { countryName: "Laos", countryCode: "LA" },
    { countryName: "Latvia", countryCode: "LV" },
    { countryName: "Lebanon", countryCode: "LB" },
    { countryName: "Lesotho", countryCode: "LS" },
    { countryName: "Liberia", countryCode: "LR" },
    { countryName: "Libya", countryCode: "LY" },
    { countryName: "Liechtenstein", countryCode: "LI" },
    { countryName: "Lithuania", countryCode: "LT" },
    { countryName: "Luxembourg", countryCode: "LU" },
    { countryName: "Madagascar", countryCode: "MG" },
    { countryName: "Malawi", countryCode: "MW" },
    { countryName: "Malaysia", countryCode: "MY" },
    { countryName: "Maldives", countryCode: "MV" },
    { countryName: "Mali", countryCode: "ML" },
    { countryName: "Malta", countryCode: "MT" },
    { countryName: "Marshall Islands", countryCode: "MH" },
    { countryName: "Mauritania", countryCode: "MR" },
    { countryName: "Mauritius", countryCode: "MU" },
    { countryName: "Mexico", countryCode: "MX" },
    { countryName: "Micronesia", countryCode: "FM" },
    { countryName: "Moldova", countryCode: "MD" },
    { countryName: "Monaco", countryCode: "MC" },
    { countryName: "Mongolia", countryCode: "MN" },
    { countryName: "Montenegro", countryCode: "ME" },
    { countryName: "Morocco", countryCode: "MA" },
    { countryName: "Mozambique", countryCode: "MZ" },
    { countryName: "Myanmar (Burma)", countryCode: "MM" },
    { countryName: "Namibia", countryCode: "NA" },
    { countryName: "Nauru", countryCode: "NR" },
    { countryName: "Nepal", countryCode: "NP" },
    { countryName: "Netherlands", countryCode: "NL" },
    { countryName: "New Zealand", countryCode: "NZ" },
    { countryName: "Nicaragua", countryCode: "NI" },
    { countryName: "Niger", countryCode: "NE" },
    { countryName: "Nigeria", countryCode: "NG" },
    { countryName: "North Korea", countryCode: "KP" },
    { countryName: "North Macedonia", countryCode: "MK" },
    { countryName: "Norway", countryCode: "NO" },
    { countryName: "Oman", countryCode: "OM" },
    { countryName: "Pakistan", countryCode: "PK" },
    { countryName: "Palau", countryCode: "PW" },
    { countryName: "Palestine", countryCode: "PS" },
    { countryName: "Panama", countryCode: "PA" },
    { countryName: "Papua New Guinea", countryCode: "PG" },
    { countryName: "Paraguay", countryCode: "PY" },
    { countryName: "Peru", countryCode: "PE" },
    { countryName: "Philippines", countryCode: "PH" },
    { countryName: "Poland", countryCode: "PL" },
    { countryName: "Portugal", countryCode: "PT" },
    { countryName: "Qatar", countryCode: "QA" },
    { countryName: "Romania", countryCode: "RO" },
    { countryName: "Russia", countryCode: "RU" },
    { countryName: "Rwanda", countryCode: "RW" },
    { countryName: "Saint Kitts and Nevis", countryCode: "KN" },
    { countryName: "Saint Lucia", countryCode: "LC" },
    { countryName: "Saint Vincent and the Grenadines", countryCode: "VC" },
    { countryName: "Samoa", countryCode: "WS" },
    { countryName: "San Marino", countryCode: "SM" },
    { countryName: "Sao Tome and Principe", countryCode: "ST" },
    { countryName: "Saudi Arabia", countryCode: "SA" },
    { countryName: "Senegal", countryCode: "SN" },
    { countryName: "Serbia", countryCode: "RS" },
    { countryName: "Seychelles", countryCode: "SC" },
    { countryName: "Sierra Leone", countryCode: "SL" },
    { countryName: "Singapore", countryCode: "SG" },
    { countryName: "Slovakia", countryCode: "SK" },
    { countryName: "Slovenia", countryCode: "SI" },
    { countryName: "Solomon Islands", countryCode: "SB" },
    { countryName: "Somalia", countryCode: "SO" },
    { countryName: "South Africa", countryCode: "ZA" },
    { countryName: "South Korea", countryCode: "KR" },
    { countryName: "South Sudan", countryCode: "SS" },
    { countryName: "Spain", countryCode: "ES" },
    { countryName: "Sri Lanka", countryCode: "LK" },
    { countryName: "Sudan", countryCode: "SD" },
    { countryName: "Suriname", countryCode: "SR" },
    { countryName: "Sweden", countryCode: "SE" },
    { countryName: "Switzerland", countryCode: "CH" },
    { countryName: "Syria", countryCode: "SY" },
    { countryName: "Taiwan", countryCode: "TW" },
    { countryName: "Tajikistan", countryCode: "TJ" },
    { countryName: "Tanzania", countryCode: "TZ" },
    { countryName: "Thailand", countryCode: "TH" },
    { countryName: "Timor-Leste", countryCode: "TL" },
    { countryName: "Togo", countryCode: "TG" },
    { countryName: "Tonga", countryCode: "TO" },
    { countryName: "Trinidad and Tobago", countryCode: "TT" },
    { countryName: "Tunisia", countryCode: "TN" },
    { countryName: "Turkey", countryCode: "TR" },
    { countryName: "Turkmenistan", countryCode: "TM" },
    { countryName: "Tuvalu", countryCode: "TV" },
    { countryName: "Uganda", countryCode: "UG" },
    { countryName: "Ukraine", countryCode: "UA" },
    { countryName: "United Arab Emirates", countryCode: "AE" },
    { countryName: "United Kingdom", countryCode: "GB" },
    { countryName: "United States of America", countryCode: "US" },
    { countryName: "Uruguay", countryCode: "UY" },
    { countryName: "Uzbekistan", countryCode: "UZ" },
    { countryName: "Vanuatu", countryCode: "VU" },
    { countryName: "Vatican City", countryCode: "VA" },
    { countryName: "Venezuela", countryCode: "VE" },
    { countryName: "Vietnam", countryCode: "VN" },
    { countryName: "Yemen", countryCode: "YE" },
    { countryName: "Zambia", countryCode: "ZM" },
    { countryName: "Zimbabwe", countryCode: "ZW" }
  ];
  